#!/usr/bin/env bash
# ============================================================
# 01mvpblog - 管理员创建和站点配置脚本
# 在你的本地终端运行此脚本完成剩余配置
# ============================================================
set -euo pipefail

SITE_URL="https://01mvpblog.dakcl.workers.dev"
ADMIN_NAME="ron"
ADMIN_EMAIL="ron@example.com"
ADMIN_PASSWORD="Admin123!@#"

echo "========================================"
echo "01mvpblog 站点配置脚本"
echo "========================================"
echo ""

# Step 1: Create first admin user
echo ">>> Step 1: 创建管理员用户..."
ADMIN_RESP=$(curl -s -D - -X POST "${SITE_URL}/api/admin/users" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"${ADMIN_NAME}\",\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}")

echo "${ADMIN_RESP}" | head -20
echo ""

# Extract cookies
SET_COOKIE=$(echo "${ADMIN_RESP}" | grep -i 'set-cookie:' | head -1 | sed 's/.*set-cookie: //i' | tr -d '\r')
echo "Cookie obtained: ${SET_COOKIE:0:50}..."

# Step 2: Get site settings
echo ""
echo ">>> Step 2: 获取站点设置..."
SITE_SETTINGS=$(curl -s "${SITE_URL}/api/site")
echo "${SITE_SETTINGS}" | python3 -m json.tool 2>/dev/null || echo "${SITE_SETTINGS}"
echo ""

# Step 3: Update site settings
echo ""
echo ">>> Step 3: 更新站点设置..."
UPDATE_RESP=$(curl -s -X PUT "${SITE_URL}/api/site" \
  -H "Content-Type: application/json" \
  -b "${SET_COOKIE}" \
  -d '{
    "name": "我的博客",
    "description": "记录与生活的个人空间",
    "authorName": "ron",
    "authorEmail": "ron@example.com",
    "authorBio": "记录技术与生活。",
    "primaryLanguage": "zh",
    "locales": ["zh", "en"],
    "themePreset": "maker",
    "layoutPreset": "shelf",
    "commentsEnabled": true,
    "commentsRequireApproval": true,
    "emailSendingEnabled": false,
    "i18n": {
      "name": {"en": "My Blog"},
      "description": {"en": "A personal space for recording life."},
      "authorBio": {"en": "Recording tech and life."}
    }
  }')
echo "${UPDATE_RESP}" | python3 -m json.tool 2>/dev/null || echo "${UPDATE_RESP}"
echo ""

# Step 4: Publish first bilingual post
echo ""
echo ">>> Step 4: 发布第一篇文章..."
POST_RESP=$(curl -s -X POST "${SITE_URL}/api/posts" \
  -H "Content-Type: application/json" \
  -b "${SET_COOKIE}" \
  -d '{
    "title": "欢迎来到我的博客",
    "slug": "hello-from-01mvpblog",
    "excerpt": "这是我的第一篇博客文章，由 01mvp-blog Skill 自动生成。",
    "content": "<h2>你好，世界！</h2><p>这是我的个人博客。在这里，我将记录技术探索和生活中的点滴。感谢你的来访！</p>",
    "status": "published",
    "tags": ["博客", "介绍"],
    "i18n": {
      "title": {"en": "Welcome to My Blog"},
      "excerpt": {"en": "This is my first blog post, auto-generated by the 01mvp-blog Skill."},
      "content": {"en": "<h2>Hello, World!</h2><p>This is my personal blog. Here I will document my tech explorations and life moments. Thanks for visiting!</p>"}
    }
  }')
echo "${POST_RESP}" | python3 -m json.tool 2>/dev/null || echo "${POST_RESP}"
echo ""

# Step 5: Create API token
echo ""
echo ">>> Step 5: 创建 API Token..."
TOKEN_RESP=$(curl -s -X POST "${SITE_URL}/api/tokens" \
  -H "Content-Type: application/json" \
  -b "${SET_COOKIE}" \
  -d '{
    "name": "automation-token",
    "scopes": ["posts:read", "posts:write", "posts:publish", "assets:write", "comments:moderate", "site:read", "site:write", "export:read"]
  }')
echo "${TOKEN_RESP}" | python3 -m json.tool 2>/dev/null || echo "${TOKEN_RESP}"
echo ""

# Step 6: Verify public pages
echo ""
echo ">>> Step 6: 验证站点..."
echo "  Homepage: $(curl -s -o /dev/null -w '%{http_code}' "${SITE_URL}")"
echo "  RSS: $(curl -s -o /dev/null -w '%{http_code}' "${SITE_URL}/rss.xml")"
echo "  Sitemap: $(curl -s -o /dev/null -w '%{http_code}' "${SITE_URL}/sitemap.xml")"
echo "  Robots: $(curl -s -o /dev/null -w '%{http_code}' "${SITE_URL}/robots.txt")"
echo "  OpenAPI: $(curl -s -o /dev/null -w '%{http_code}' "${SITE_URL}/openapi.json")"

echo ""
echo "========================================"
echo "✅ 站点配置完成！"
echo ""
echo "🔗 访问你的博客: ${SITE_URL}"
echo "🔗 管理后台: ${SITE_URL}/admin"
echo "👤 管理员邮箱: ${ADMIN_EMAIL}"
echo "🔑 管理员密码: ${ADMIN_PASSWORD}"
echo ""
echo "⚠️  请尽快登录后台修改密码！"
echo "========================================"
